# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: 'API_MercaditoTEC/API_MercaditoTEC.sln'
    arguments: '--confirguration $(buildConfiguration)'

- script: dotnet build API_MercaditoTEC --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

  #Packaging
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish API_MercaditoTEC --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'API_MercaditoTEC/API_MercaditoTEC.sln'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'
